---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by werdn.
---
local dao = require('db')
local RPS = os.getenv('RPS')
local digest = require('digest')
local log = require('log')

lastCallTime = 0
requests = 0
maxRequests = tonumber(RPS)
local check = {
    rps = function(self)
        local result = true
        local callTime = os.time()
        if os.difftime(callTime, lastCallTime) == 0 then
            requests = requests + 1
            if requests > maxRequests then
                result = false
            end
        else
            requests = 1
        end
        lastCallTime = callTime
        return result
    end,

    auth = function(self, req)
        if req.headers['authorization'] == nil then
            return false
        else
            local auth = string.sub(req.headers['authorization'], 7)
            local decoded = digest.base64_decode(auth)
            local user, pwdHash = decoded:match("([^:]+):([^:]+)")
            if user == nil or pwdHash == nil then
                return false
            else
                local user = dao:findUser(user)
                if digest.sha256_hex(pwdHash) ~= user[2] then
                    return false
                elseif string.find(user[3], req.method) == nil then
                    return false
                else
                    return true
                end
            end
        end
    end
}

return check